### ISSUE TITLE
How to run the eevm after compilation

### ISSUE THREAD

**Issue by gbaduz** [Microsoft/eEVM#10]
Is there any sample code that shows how to pass a bytecode to the evm and run it. I noticed that it is possible through the test case samples. I will be glad to see how to execute the code without the test harness.

Thank you

**Comment by eddyashton** [comment]
We don't have a standalone eEVM app or sample that will run arbitrary bytecode, but there are some simpler examples than the test harness [in the vmExecution test case of tests/main.cpp](https://github.com/Microsoft/eEVM/blob/ad50aa279c08db3a183674478275eb82184cf025/tests/main.cpp#L223).

In the add subcase, we create an `evm::Processor` with all 'permanent' state in a `std::map`
```
SimpleGlobalState gs;
...
Processor p(gs);
```
then we create some bytecode that will add 2 numbers together and return the result, and deploy this to an address
```
const std::vector<uint8_t> code = {...};
gs.create(to, {}, code);
```
and finally we run the bytecode by running a transaction with that address as the callee
```
const auto e = p.run(tx, from, gs.get(to), {}, 0, &tr);
```

Hope that helps.

**Comment by eddyashton** [comment]
Update: #13 adds some examples in the [samples](https://github.com/Microsoft/eEVM/tree/master/samples) directory. These should provide a more complete introduction.
