### ISSUE TITLE
Do you have an EVM-C integration?

### ISSUE THREAD

**Issue by bobsummerwill** [Microsoft/eEVM#14]
Do you have an implementation of an EVM-C wrapping of eEVM somewhere which could be published, so we can try using eEVM within Geth or similar on the Ethereum mainnet or testnets?  Thanks!

**Comment by eddyashton** [comment]
We don't have an EVM-C wrapping. We may look at building one in the new year if we have time, but this kind of integration isn't a high priority for us.

**Comment by bobsummerwill** [comment]
Hey Eddy - thanks for the info.

I have an email thread running with Cale Teeter, Marley Grey and Yorke Rhodes talking about eEVM, and I would love to bring you onto that too.  We have worked together on Ethereum topics since 2016, first when I was at the EF, and then within the context of the EEA.

Please could you drop me a mail at bob@summerwill.net?  Thanks!
