### ISSUE TITLE
TEE implementation of eEVM

### ISSUE THREAD

**Issue by infobiac** [Microsoft/eEVM#18]
Is there an implementation of eEVM running in an enclave using the openenclave sdk publicly available? I'm trying to get it running, and have a few issues/questions:

- Making all the standard libraries/boost available: I'm interested to see how this was accomplished in order to minimize the enclave's TCB
- I'd love to see the edl, to get a better understanding of what functions are where etc.

Maybe my understanding of both this project and openenclave/there relationship are incorrect.

**Comment by eddyashton** [comment]
We don't currently have a standalone demo of this - we do run inside a TEE using OpenEnclave, but only embedded within a larger application. In brief; we build a position-independent library from the eEVM source files, adding the boost, OE libcxx and libc include directories, and link this against the OE libs (the boost dependency is header-only, else we'd need to build our own position-independent 'enclave-friendly' version of that).

I think it's a good to have a public demo of this, so we'll give it some more thought.

**Comment by infobiac** [comment]
Thanks, that worked for me. As a follow up: was any work done to lessen the TCB? It seems like with the boost/json/keccak dependencies, the TCB would end up quite large.

**Comment by eddyashton** [comment]
I'm glad that was helpful.

We didn't do anything else to minimise the TCB. Compared to OpenEnclave and the std libraries, these extra dependencies are reasonably small.

Ideally these things should be completely modular and pluggable, so users can choose to trust some third party solution or to build their own. This is something we'd like to do for the boost dependency (writing our own big-int library), and could be done for Keccak (though we're unlikely to get something as small and fast as the XKCP solution). I believe json isn't actually needed inside the eEVM, only for the tests - so it should be possible to pull that out of the trusted enclave library.

If we want a truly minimal TCB, we'd really need to extend this to the std library and allow users to plug-in trusted container types as well. We're interested to see how important this TCB control is to users. But on the tradeoff between "how much code do I need to read to trust this library" and "how much work do I save by using this library", we're veryhappy with nlohmann::json and Keccak.

**Comment by infobiac** [comment]
Thank you for that explanation, that makes sense to me!
