### ISSUE TITLE
Cannot build on Linux following README.md

### ISSUE THREAD

**Issue by hikame** [Microsoft/eEVM#3]
I have got the following error.
`$ cmake -GNinja ..
CMake Error at CMakeLists.txt:3 (project):
  Running

   '/usr/sbin/ninja' '--version'

  failed with:

   die: error: must run as root
`
cmake version 3.11.2
ninja version 0.1.3 initializing

But the following commands works for me:
`mkdir build

cd build

cmake ..

make
`

**Comment by achamayou** [comment]
You want want /usr/bin/ninja (apt install ninja-build, https://ninja-build.org/), not /usr/sbin/ninja (apt install ninja), a similarly named but unrelated tool.
