### ISSUE TITLE
Linux build instructions...

### ISSUE THREAD

**Issue by gskapka** [Microsoft/eEVM#4]
On Ubuntu 18.04 the instuctions:

```
mkdir build; cd build
cmake -GNinja ..
ninja
```

...builds the file `build.ninja` in the root, not the build folder, & nor is it called `ninja.

**Comment by achamayou** [comment]
Can you provide additional detail? These instructions work as far as we can tell.

```
~$ git clone https://github.com/Microsoft/eEVM.git
Cloning into 'eEVM'...
...
Resolving deltas: 100% (43/43), done.
~$ cd eEVM/
~/eEVM$ mkdir build; cd build
~/eEVM/build$ cmake -GNinja ..
...
-- Configuring done
-- Generating done
-- Build files have been written to: ~/eEVM/build
~/eEVM/build$ ls build.ninja 
build.ninja
```

ninja is a build tool (https://ninja-build.org/) you will need to install, on Ubuntu 18.04, you can simply run:

```
sudo apt install ninja-build
```

If you find it difficult to use ninja, you can use make instead:

```
mkdir build; cd build
cmake ..
make
```

**Comment by gskapka** [comment]
Okay - sorted now, thank you very much @achamayou !
