### ISSUE TITLE
Add abstract Account

### ISSUE THREAD

**Issue by eddyashton** [microsoft/eEVM#42]
Most of the eEVM's execution goes to virtual methods, allowing clients to implement global state + storage access logic, and handle each request however they wish. One place we don't have this is in `Account` - we currently hold a specific struct, and access its fields directly in the `Processor`.

Instead, `Account` should become a `Storage` like interface. The current implementation can become `SimpleAccount`, but other clients with different requirements can provide and store the account state any way they want _at the call point_.

**Comment by unboxedtype** [comment]
My 50 cents: I noticed eEVM project among other EVM-related projects because of its simple and concise design. New abstraction layers can introduce extra complexity, and it is not at all obvious if the feature will be appreciated by the end-users. Please keep it simple as long as possible.

**Comment by eddyashton** [comment]
Thanks for the feedback @unboxedtype, we'll take it into consideration.

In this case I think the tradeoff is reasonable - its the same abstraction pattern we already have with GlobalState and Storage, and the current implementation will remain available for users who want the simplest interface. It will make some of our downstream use cases much easier.
