### ISSUE TITLE
`to_big_endian` does not work well in SGX environment

### ISSUE THREAD

**Issue by Liaojinghui** [microsoft/eEVM#54]
I tried to run eEVM in SGX, but every time I call `to_big_endian` in the byte to byte mode, no matter how long the input array is, the output will only have 8 valid bytes, the rest remains 0. I also checked the source code and find out that the `>>` only moves the first 8 bytes. By the way, the host operating system that I am running is Ubuntu 18.04 64 bits.

**Comment by eddyashton** [comment]
I'm surprised by this - this works in our enclaved apps. I've just run a quick test based on our `byteExport` unit test inside an enclave and confirmed that this writes the entire value, regardless of the alignment (ie, when using the byte-by-byte path). Can you give me a code sample demonstrating the issue?

Separately, I'm looking at replacing our Boost dependency with `intx`, which will replace this `to_big_endian` implementation entirely. So if there's some compiler/platform dependency in the current path that I can't see, it may be removed soon!

**Comment by eddyashton** [comment]
Closing as inactive, and hopefully resolved by #55.
