### ISSUE TITLE
build failed on Windows 10 with visual studio 2017

### ISSUE THREAD

**Issue by chunfu-yang** [Microsoft/eEVM#6]
got following error message. Is there any other MACRO or third party libraries are needed? 
fatal error C1083: Cannot open include file: 'nlohmann/json.hpp': No such file or dir
ectory [D:\eEVM\eEVM\evm.vcxproj]

My build environment:
Windows 10
Visual Studio 2017 Community
Boost 1.67.0

**Comment by eddyashton** [comment]
This third party header should be present. If you have cloned the entire repo, it will be under `3rdparty/nlohmann/json.hpp`. If you're using cmake and the provided CMakeLists.txt, that will generate projects which include the path to `3rdparty` in the build include directories:

<pre>
H:\eEVM\eEVM\build>msbuild evm.vcxproj
<...>
ClCompile:
  C:\<...>\CL.exe /c <b>/IH:\eEVM\eEVM\3rdparty</b> <...>
</pre>

If making your own build project you'll need to add the path to `3rdparty`.

Recommended VS2017 build steps repeated here for clarity:
```
mkdir build
cd build
cmake -DBoost_INCLUDE_DIR=<boost directory> ..
msbuild ALL_BUILD.vcxproj
```
