### ISSUE TITLE
How does the eEVM interact with other nodes if it runs in the EVM?

### ISSUE THREAD

**Issue by nathanawmk** [Microsoft/eEVM#7]
Hi all, 

Might be a silly question. How does the eEVM interact with other nodes/outside world if it runs in the completely in the eEVM? How does it connect with other nodes to sync its ledger? 

Nathan Aw

**Comment by flxflx** [comment]
Hi Nathan, 
are you asking how eEVM is going to communicate and sync its ledger when it is running in an enclave/TEE? The short answer is: eEVM is a pretty bare bones implementation of the EVM. It doesn't really know about a ledger and other nodes. One needs to provide eEVM with implementations of the abstract GlobalState and Storage classes. Those implementations are then responsible for sync'ing etc. With regard to sync'ing, technically there isn't a really a difference between running inside or outside an enclave.
Hope this helps.

**Comment by nathanawmk** [comment]
> Hi Nathan,
> are you asking how eEVM is going to communicate and sync its ledger when it is running in an enclave/TEE? The short answer is: eEVM is a pretty bare bones implementation of the EVM. It doesn't really know about a ledger and other nodes. One needs to provide eEVM with implementations of the abstract GlobalState and Storage classes. Those implementations are then responsible for sync'ing etc. With regard to sync'ing, technically there isn't a really a difference between running inside or outside an enclave.
> Hope this helps.

Thanks! yes, my question is on how eEVM to communicate and sync its ledger. And if enclaves could crunch so much data and run the contracts. 

Thank you. 

Nathan
