### ISSUE TITLE
how to use the enclave EVM in the SGX enclave to execute smart contract

### ISSUE THREAD

**Issue by knight-hjh** [microsoft/eEVM#70]
I try to use the enclave EVM in the enclave of SGX. When I include the EVM file in the enclave, it will report some mistakes, because the EVM file include other files which can not be found in the enclave. I am confused. Due to the limitation of enclave, how can I use the enclave EVM in the enclave.

**Comment by Yeuman** [comment]
I encountered the same question!

**Comment by knight-hjh** [comment]
> I encountered the same question!

Have you tried any other methods?

**Comment by Yeuman** [comment]
> > I encountered the same question!
> 
> Have you tried any other methods?

I know the rust-sgx-sdk from Baidu X lab implemented EVM internally. But I'm a freshman and not familiar with rust.

**Comment by Yeuman** [comment]
> > I encountered the same question!
> 
> Have you tried any other methods?

老哥，加个微信哈哈哈哈哈？

**Comment by knight-hjh** [comment]
可以的18291869074


发自我的iPhone

------------------ Original ------------------
From: Yeuman ***@***.***&gt;
Date: 周五,4月 23,2021 2:44 下午
To: microsoft/eEVM ***@***.***&gt;
Cc: knight-hjh ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [microsoft/eEVM] how to use the enclave EVM in the SGX enclave to execute smart contract (#70)





   
I encountered the same question!
  
Have you tried any other methods?
  
老哥，加个微信哈哈哈哈哈？

**Comment by eddyashton** [comment]
Can you share some more details of how you're trying to build eEVM?
Are you using CMake?
What SGX SDK are you using?

If it can't find files that _probably_ means missing include directories - you'll need to add the `eEVM/3rdparty` and `eEVM/include` directories to your include paths to build the `eEVM` source files.

**Comment by eddyashton** [comment]
If you're using OpenEnclave, there was a previous issue #63 which resulted in [a sample repo](https://github.com/liangyihuai/EVM_in_Openenclave) demonstrating how to compile eEVM to run on top of OpenEnclave. This may be a useful starting point, though I believe it was targeting an old version of OpenEnclave.

**Comment by knight-hjh** [comment]
![image](https://user-images.githubusercontent.com/38315608/115869577-a5ce8680-a470-11eb-804d-90fbc583bf5f.png)

**Comment by knight-hjh** [comment]
I use Intel SGX SDK. I've built two projects, the normal C + + project and the Intel SGX enclave project. I want to call the function in enclave from the common c++ project, which can run the smart contract. At that time, EVM is needed in Enclave to run the smart contract. But when I am in Include EVM related file in enclave, it always report that the include files contained in the file can not be found.

**Comment by knight-hjh** [comment]
![Uploading image.png…]()

**Comment by knight-hjh** [comment]
![image](https://user-images.githubusercontent.com/38315608/115873012-08298600-a475-11eb-908f-830194f225c7.png)

**Comment by Yeuman** [comment]
I built `eEVM` successfully using `CMake` and got `libeevm.a`. The samples works well, too. Then I tried to embed `eEVM` in my project by adding `libeevm.a` to the library path and adding `eEVM/3rdparty` and `eEVM/include`  to the include path. However, it doesn't work. 

I am using `Intel SGX SDK` and running on `Ubuntu 18.04`.
I built my project with `Makefile`. 

Here are some details of my project. (The paths of `eEVM/3rdparty` and `eEVM/include`  are included using `-I` in Makefile)

```
.
├── App
│   ├── App.cpp
│   └── App.h
├── Enclave
│   ├── Enclave.config.xml
│   ├── Enclave.cpp
│   ├── Enclave.edl
│   ├── Enclave.h
│   ├── Enclave.lds
│   ├── Enclave_private.pem
│   └── HelloEVM.cpp
├── Include
│   └── user_types.h
├── lib
│   └── libeevm.a
├── Makefile
├── _qall
├── README.md
└── README.txt
```
The followings are some errors I encountered. It seems the head files are suffering compilation fails in Intel SGX environment. So is there any example projects built on top of `Intel SGX SDK`? Any suggestions will be appreciated. 
```
/home/ymy/Code/eEVM/include/eEVM/disassembler.h:165:14: error: ‘stringstream’ is not a member of ‘std’
         std::stringstream comment;
              ^~~~~~~~~~~~
/home/ymy/Code/eEVM/include/eEVM/disassembler.h:172:11: error: ‘comment’ was not declared in this scope
           comment << "illegal target";
           ^~~~~~~
/home/ymy/Code/eEVM/include/eEVM/disassembler.h:174:11: error: ‘comment’ was not declared in this scope
           comment << "branches to " << target->second->comment;
           ^~~~~~~
/home/ymy/Code/eEVM/include/eEVM/disassembler.h:175:25: error: ‘comment’ was not declared in this scope
         jump->comment = comment.str();
                         ^~~~~~~
In file included from /home/ymy/Code/eEVM/include/eEVM/stack.h:9:0,
                 from /home/ymy/Code/eEVM/include/eEVM/trace.h:7,
                 from /home/ymy/Code/eEVM/include/eEVM/processor.h:8,
                 from Enclave/HelloEVM.cpp:4:
/home/ymy/Code/eEVM/3rdparty/fmt/ostream.h: At global scope:
/home/ymy/Code/eEVM/3rdparty/fmt/ostream.h:18:46: error: expected template-name before ‘<’ token
 class formatbuf : public std::basic_streambuf<Char> {
                                              ^
/home/ymy/Code/eEVM/3rdparty/fmt/ostream.h:18:46: error: expected ‘{’ before ‘<’ token
/home/ymy/Code/eEVM/3rdparty/fmt/ostream.h:49:40: error: expected template-name before ‘<’ token
 struct test_stream : std::basic_ostream<Char> {
                                        ^
/home/ymy/Code/eEVM/3rdparty/fmt/ostream.h:49:40: error: expected ‘{’ before ‘<’ token
/home/ymy/Code/eEVM/3rdparty/fmt/ostream.h:76:17: error: variable or field ‘write’ declared void
 void write(std::basic_ostream<Char> &os, basic_buffer<Char> &buf) {
                 ^~~~~~~~~~~~~
/home/ymy/Code/eEVM/3rdparty/fmt/ostream.h:76:17: error: ‘basic_ostream’ is not a member of ‘std’
/home/ymy/Code/eEVM/3rdparty/fmt/ostream.h:76:35: error: expected primary-expression before ‘>’ token
 void write(std::basic_ostream<Char> &os, basic_buffer<Char> &buf) {
```

**Comment by Yeuman** [comment]
@eddyashton

**Comment by eddyashton** [comment]
@Yeuman eEVM uses several things from the C++ standard library, including `std::stringstream`, but this is apparently [not available in the SGX SDK](https://www.intel.co.uk/content/www/uk/en/support/articles/000058765/software/intel-security-products.html).

These string formatters (`3rdparty`, `std::ostream& operator<<`, etc) are only used for debug printing, not for functionality, so it should be possible to build without them. However this will require some source modifications.

I'll look at adding a `#define` to disable these functions when I find the time. This may not be sufficient to build on top of the Intel SGX SDK however, as there may be other std library types which are not available.

**Comment by Yeuman** [comment]
> @Yeuman eEVM uses several things from the C++ standard library, including `std::stringstream`, but this is apparently [not available in the SGX SDK](https://www.intel.co.uk/content/www/uk/en/support/articles/000058765/software/intel-security-products.html).
> 
> These string formatters (`3rdparty`, `std::ostream& operator<<`, etc) are only used for debug printing, not for functionality, so it should be possible to build without them. However this will require some source modifications.
> 
> I'll look at adding a `#define` to disable these functions when I find the time. This may not be sufficient to build on top of the Intel SGX SDK however, as there may be other std library types which are not available.

Thanks for your help!!
