### ISSUE TITLE
Can't compile with glibc master: SIGSTKSZ is no longer a constant 

### ISSUE THREAD

**Issue by Masheenist** [microsoft/eEVM#71]
Couldn't build because this error popped up:
error: size of array 'altStackMem' is not an integral constant-expression
 4189 |         static char             altStackMem[4 * SIGSTKSZ];

Easily fixed by using the latest version of doctest.h. I can't create a pull request though, so maybe someone with access can update?

**Comment by eddyashton** [comment]
@Masheenist Thanks for raising. You should be able to create a pull request, as this is a public repo. You won't be able to create a branch on this fork (to avoid spamming all cloners with other people's work branches), but you should be able to open a cross-fork PR from a branch on your own fork. Please let me know if that doesn't work, and I'll take another look at the protection settings!

**Comment by Masheenist** [comment]
Thanks for the help! I was just about to do this but I see that you are on
the ball, lol.
