### ISSUE TITLE
Guides

### ISSUE THREAD

**Issue by sartimo** [Microsoft/eEVM#79]
Hello All

do you provide any docs on integrating eEVM into existing systems like UTXO or Cryptonote or similar ledgers?

thanks and br

timo

**Comment by eddyashton** [comment]
Hi @sartimo. We don't have any further documentation. One project that may be useful is [EVM-for-CCF](https://github.com/microsoft/EVM-for-CCF), which demonstrates embedding eEVM in a larger project. However that is archived, and likely unhelpful of you're looking for integration with existing Ethereum ledgers.
